### ISSUE TITLE
amount of test set

### ISSUE THREAD

**Issue by phoenixsecularbird** [prajjwal1/discosense#2]
Hello! How many samples are there in the test set? According to your paper, the number  is 3757. However, I only get 3753 samples. And I find that the samples with id of 200, 248, 249 and 250 are missing. Thank you!

**Comment by prajjwal1** [comment]
Thank you for bringing this up. I've added the missing examples. You can now pull the data but before you do that, you would have to clear the cache (in case you're using HF datasets).

**Comment by phoenixsecularbird** [comment]
OK! Thank for your response!
